### ISSUE TITLE
Editor: egui only

### ISSUE THREAD

**Issue by steflon19** [villor/bevy_lookup_curve#9]
Consider egui only feature flag to make `lookup_curve` usable without `bevy`dependency

**Comment by steflon19** [comment]
I used your crate in an egui app for a LUT editor, which works very nice. Problem is that it introduces a dependency on `bevy`, which I am not really using. Would it be possible to split the editor into a `egui-only` feature flag? 

I gave it a short try for a pull request but wasn't quite sure how the split would make sense.

**Comment by villor** [comment]
Hi! I’m glad you find it useful.
It makes a lot of sense that one might want to use this outside of bevy as well. There is another issue #2 for separating the crate into more features.

I think it would be easier to add features that adds the different parts of bevy (bevy is pretty modular and divided into different crates), rather than a feature that conditionally removes the bevy dependencies.

I’ll take a look at the dependencies to see if I can come up with a feature division that makes sense. I’m a bit short on time currently so I hope you’re fine using it with the bevy deps for now. Otherwise I would advise you to fork it and remove anything bevy in the meantime. (Keep bevy_math to make it easier, but set default-features = false)

**Comment by villor** [comment]
@steflon19 v0.4 is now live, which adds a bunch of new features to make it easier to reduce dependencies.

To use without bevy (except bevy_math, which is a core dependency) just set default-features = false. And enable `serialize`, `ron`, and/or `editor_egui` if needed.

See the egui_only example. It can also be used as a standalone curve editor.

**Comment by steflon19** [comment]
Wow this was super fast, thanks a lot for looking into this and providing an version with reduced dependencies that quickly!

**Comment by steflon19** [comment]
hey @villor , may I suggest a followup to the "egui-only" feature gate? When I am trying to use it like described, I am getting errors here:

```  
error: cannot find attribute `reflect` in this scope
 --> /home/steflon/code/muybridge/bevy_lookup_curve/src/lib.rs:260:7
    |
260 |     #[reflect(default = "max_error_default")]
    |       ^^^^^^^

error: cannot find attribute `reflect` in this scope
   --> /home/steflon/code/muybridge/bevy_lookup_curve/src/lib.rs:256:7
    |
256 |     #[reflect(default = "max_iters_default")]
    |       ^^^^^^^

error: cannot find attribute `reflect` in this scope
   --> /home/steflon/code/muybridge/bevy_lookup_curve/src/lib.rs:135:7
    |
135 |     #[reflect(skip_serializing, default = "unique_knot_id")]
    |       ^^^^^^^ 
```


I guess the cfg_attr before usage for `reflect` is missing in `lib.rs` like this:

```
    #[serde(skip_serializing, default = "unique_knot_id")]
    #[cfg_attr(
        feature = "bevy_reflect",
        reflect(skip_serializing, default = "unique_knot_id")
    )]
    pub id: usize,
```
instead of 
```
    #[serde(skip_serializing, default = "unique_knot_id")]
    #[reflect(skip_serializing, default = "unique_knot_id")]
    pub id: usize,
```



That is, either this or add `bevy_reflect` as a required feature :)

**Comment by villor** [comment]
Right! I totally forgot about that one. Thanks for letting me know, I’ll fix this as soon as I can.

I guess from now on I should do more thorough build tests 😅

**Comment by villor** [comment]
New version is up. This should now be fixed 🤞

I can recommend https://github.com/frewsxcv/cargo-all-features by the way. Helped tremendously to hunt down any build errors.
